name = "c-it-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "c-it-backend-prod"

[env.staging]
name = "c-it-backend-staging"

[[env.production.kv_namespaces]]
binding = "C_IT_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[env.staging.kv_namespaces]]
binding = "C_IT_KV"
id = "your-staging-kv-namespace-id"
preview_id = "your-staging-preview-kv-namespace-id"

[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"

[env.production.r2_buckets]
binding = "C_IT_BUCKET"
bucket_name = "c-it-assets"

[env.staging.r2_buckets]
binding = "C_IT_BUCKET"
bucket_name = "c-it-assets-staging" 